config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :posts do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  #Uploader definition
   mount_uploader :image, ImageUploader
   validates :image, presence: true
    validates :content, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # validates :name,  presence: true, length: { maximum: 30 }
    validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
    before_validation { email.downcase! }
    # has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]
  # before_action :user_login_check, only: [:new]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    if params[:back]
    @post = Post.new(post_params)
  else
    @post = Post.new
    end
   end

   def confirm
     @post = current_user.posts.build(post_params)
     @user = @post.user
       render :new if @post.invalid?
     end
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
     @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm' || action_name == 'create' || action_name =='show'
        confirm_posts_path
      elsif action_name == 'edit'
        post_path
      end
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebookclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <header>
    Facebook
    </header>
  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/ideas">Ideas</a>
    </li>
    ...
  </ul>
  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    <p id="notice"><%= notice %></p>
    <footer>
    <p>© 2021 Copyright Facebook clone project</p>
      </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url, size: 17*17) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
   </div>
   <div class="field">
     <%= form.label :content %>
     <%= form.text_area :content %>
   </div>
   <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h1>Do you want to post this ?</h1>

<%= form_with(model: @post, url: posts_path, local: true) do |form| %>

<%= form.hidden_field :content %>
<p>Content: <%= @post.content %></p>
<%= image_tag(@post.image.url, size: 17*17) if @post.image && @post.image.url %>
<%= form.hidden_field :image_cache %>
<%= form.submit "Post" %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
<%= form.hidden_field :image_cache %>
<%= form.submit "Do not post", name: 'Back' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= image_tag post.image.url, style:"width:100px;height:80px" %></td>
        <td><%= post.content %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to 'Show', post,style:'padding:5px', data: { confirm: 'Are you sure?'} %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_post_path(post),style:'padding:5px', data: { confirm: 'Are you sure?' }  %></button></td>
        <td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-success"><%= link_to 'New Post', new_post_path %></button>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Images:</strong>
  <%= image_tag @post.image.url,style:'width:100px' %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>